/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.deitel.messenger;

import com.deitel.messenger.keys.Asymmetric_RSA;
import com.deitel.messenger.sockets.client.PacketSendingRequestThread;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.security.PublicKey;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

public class ClientGUI2 extends javax.swing.JFrame {

    public ClientGUI2() {
        initComponents();
        this.mapaPaineis = new HashMap<String, List<Component>>();
        
        //Carregar os contatos do Arquivo
        this.loadContacts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PainelAbas = new javax.swing.JTabbedPane();
        PainelInterior = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CaixaTexto = new javax.swing.JTextPane();
        BotaoEnviar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Conversa = new javax.swing.JTextPane();
        Cripto1 = new javax.swing.JRadioButton();
        Cripto2 = new javax.swing.JRadioButton();
        Cripto3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CaixaTexto.setAutoscrolls(false);
        CaixaTexto.setEnabled(false);
        jScrollPane2.setViewportView(CaixaTexto);

        BotaoEnviar.setText("Enviar");
        BotaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEnviarActionPerformed(evt);
            }
        });

        Conversa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Conversa.setFocusable(false);
        jScrollPane3.setViewportView(Conversa);

        buttonGroup1.add(Cripto1);
        Cripto1.setSelected(true);
        Cripto1.setText("Sem Criptografia");
        Cripto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cripto1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Cripto2);
        Cripto2.setText("Chave Simétrica");
        Cripto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cripto2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Cripto3);
        Cripto3.setText("Chave Assimétrica");
        Cripto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cripto3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelInteriorLayout = new javax.swing.GroupLayout(PainelInterior);
        PainelInterior.setLayout(PainelInteriorLayout);
        PainelInteriorLayout.setHorizontalGroup(
            PainelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInteriorLayout.createSequentialGroup()
                .addGroup(PainelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(PainelInteriorLayout.createSequentialGroup()
                        .addComponent(Cripto1)
                        .addGap(18, 18, 18)
                        .addComponent(Cripto2)
                        .addGap(18, 18, 18)
                        .addComponent(Cripto3)
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane3)
        );
        PainelInteriorLayout.setVerticalGroup(
            PainelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInteriorLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelInteriorLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cripto1)
                            .addComponent(Cripto2)
                            .addComponent(Cripto3)))))
        );

        PainelAbas.addTab("Inicie uma conversa", PainelInterior);

        jButton1.setText("Adicionar Contato");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item1", "item2", "item3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelAbas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() == 2)
        {            
            //Duplo ou Triplo clique detectado
            int index = jList1.locationToIndex(evt.getPoint());
            String textoAba = this.jList1.getModel().getElementAt(index);
            
            //Se a aba já existir, apenas deixá-la visível
            for(int i = 0; i < PainelAbas.getTabCount(); i++)
            {
                if(PainelAbas.getTitleAt(i).equals(textoAba))
                {
                    PainelAbas.setSelectedIndex(i);
                    return;
                }
                
            }
            
            this.abreNovaAba(textoAba);
            
            //Tentar remover a primeira aba
            PainelAbas.remove(PainelInterior);
            PainelAbas.setSelectedIndex(PainelAbas.getComponentCount()-1);
        }
        
    }//GEN-LAST:event_jList1MouseClicked

    private void BotaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEnviarActionPerformed
        // Exibir o texto na página e enviá-lo ao servidor
        String mensagem;
        List<Component> dadosAbaAtiva;
        int cryptoType = 1;
        
        //id from nick_to crypto type msg_type msg_text
        
        //Pegar a aba que está ativa
        String AbaAtiva = PainelAbas.getTitleAt(PainelAbas.getSelectedIndex());
        
        //Pegar a instância da caixa de texto da aba ativa na lista e daí pegar a mensagem
        dadosAbaAtiva = this.mapaPaineis.get(AbaAtiva);
        JTextPane caixaTexto = (JTextPane) dadosAbaAtiva.get(2);
        String textoMensagem = caixaTexto.getText();
        byte[] textoCriptografado;
        String textoMensagemCripto = "";
        String textoMensagemCriptoView = "";
        
        //Pegar data e hora atuais
        SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date dttm = new Date();
        
        //Tratar criptografia
        if(((JRadioButton) dadosAbaAtiva.get(3)).isSelected())
        {
            //Sem criptografia
            //O texto da mensagem não sofre alteração, nenhuma mensagem é mandada antes - As ações ocorrem abaixo
            cryptoType = 1;
            textoMensagemCripto = textoMensagem;
        }
        
        if(((JRadioButton) dadosAbaAtiva.get(4)).isSelected())
        {
            //Criptografia de Chave Simétrica
            //Se a chave da instância for null, gerar uma chave para criptografar a mensagem e enviá-la ao destinatário
            cryptoType = 2;
            
            if(this.chaveSimetrica == null)
            {
                Random r = new Random();
                
                //gerar uma chave de 256 bits -> 32 caracteres
                char[] chave = new char[16];
                int num;
                
                for(int i = 0; i < 16; i++)
                {
                    num = r.nextInt(16);
                    chave[i] = hexa[num];
                }
                
                this.chaveSimetrica = String.valueOf(chave);
                
                //Colocar na janela a mensagem de que a chave foi gerada e enviada
                dttm = new Date();
                this.appendKeyText(this.userName, cryptoType, fmt.format(dttm), (JPanel) PainelAbas.getSelectedComponent());
                
                //Enviar a chave para o destinatário
                messageManager.sendMessage(Integer.toString(this.userId), AbaAtiva, String.valueOf(cryptoType), "2", this.chaveSimetrica);

            }
            
            try 
            {
                //Criptografar agora a mensagem em AES com a chave selecionada
                textoMensagemCripto = Arrays.toString(ClientGUI2.ChaveSimetricaEncrypt(textoMensagem, this.chaveSimetrica));
            }
            catch (Exception ex) 
            {
                System.out.println(ex);
            }
        }
        
        //Criptorafia de chave assimétrica
        if(((JRadioButton) dadosAbaAtiva.get(5)).isSelected())
        {
            //Criptografia de chave assimétrica
            cryptoType = 3;
            
            //Verificar se existe chave pública para o contato em questão
            PublicKey chavePublicaUser = Asymmetric_RSA.obterChaveContato(AbaAtiva);
            boolean first = true;
            
            while(chavePublicaUser == null)
            {
                System.out.println("TáNoWhile");
                
                //Se não houver chave pública, solicitar ao servidor
                messageManager.sendRSAPublicKeyReq(AbaAtiva);

                //Exibir na tela a mensagem: Solicitando chave pública ao servidor
                if(first)
                {
                    this.appendInformText("Solicitando chave pública do destinatário ao servidor");
                    first = false;
                }

                //Dormir um segundo para dar tempo de a mensagem chegar
                try{
                    Thread.sleep(1000);
                }
                catch(Exception e){
                    System.out.println(e);
                }
                
                chavePublicaUser = Asymmetric_RSA.obterChaveContato(AbaAtiva);
                
                //Quando obter, escrever a chave na tela
                if(chavePublicaUser != null)
                    this.appendInformText("Chave Pública recebida: \r\n" + chavePublicaUser.toString());
            }
            
            //Criptografar o texto
            textoCriptografado = Asymmetric_RSA.criptografa(textoMensagem, chavePublicaUser);
            textoMensagemCripto = Arrays.toString(textoCriptografado);
            textoMensagemCriptoView = String.valueOf(textoCriptografado);
        }
        
        //imputar a mensagem na tela
        dttm = new Date();
        this.appendText(this.userName, cryptoType, fmt.format(dttm), textoMensagem, textoMensagemCripto, (JPanel) PainelAbas.getSelectedComponent());
        
        //Mandar mensagem
        messageManager.sendMessage(Integer.toString(this.userId), AbaAtiva, String.valueOf(cryptoType), "1", textoMensagemCripto); 
        
        //Limpar a aba de conversa
        caixaTexto.setText("");
    }//GEN-LAST:event_BotaoEnviarActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

    }//GEN-LAST:event_jList1ValueChanged

    private void Cripto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cripto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cripto1ActionPerformed

    private void Cripto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cripto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cripto3ActionPerformed

    private void Cripto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cripto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cripto2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static ClientGUI2 InterfaceUsuario (MessageManager messageManager) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        ClientGUI2 retorno = new ClientGUI2();
        retorno.setMessageManager(messageManager);
        retorno.setVisible(true);
        
        ClientGUI2.janelaAtual = retorno;

        return retorno;

    }
    
    public void loadContacts()
    {
        File arqContatos = new File("files/contatos.rp2");
        
        if(arqContatos.exists())
        {
            String contato;
            
            try
            {
                FileReader reader = new FileReader(arqContatos);
                BufferedReader reader2 = new BufferedReader(reader);
                DefaultListModel model = new DefaultListModel<String>();
                
                
                while((contato = reader2.readLine()) != null)
                    model.addElement(contato);
                
                jList1.setModel(model);
                
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEnviar;
    private javax.swing.JTextPane CaixaTexto;
    private javax.swing.JTextPane Conversa;
    private javax.swing.JRadioButton Cripto1;
    private javax.swing.JRadioButton Cripto2;
    private javax.swing.JRadioButton Cripto3;
    private javax.swing.JTabbedPane PainelAbas;
    private javax.swing.JPanel PainelInterior;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    
    //Variaveis de controle de pagina
    public static ClientGUI2 janelaAtual;
    private HashMap<String,List<Component>> mapaPaineis;
    private String userName;
    private int userId;
    private MessageListener messageListener;
    private MessageManager messageManager;
    private PacketSendingRequestThread atualizacao;
    String chaveSimetrica;
    private final static char[] hexa = {'0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'};
    private final static String IV = "AAAAAAAAAAAAAAAA";

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
        
        this.atualizacao.setUserId(userId);
        
        //Startar a thread de atualizacao
        this.atualizacao.start();
                
        //Carregar as chaves Assimétricas
        Asymmetric_RSA.iniciarChaves();
    }

    public MessageListener getMessageListener() {
        return messageListener;
    }

    public void setMessageListener(MessageListener messageListener) {
        this.messageListener = messageListener;
    }

    public MessageManager getMessageManager() {
        return messageManager;
    }

    public void setMessageManager(MessageManager messageManager) {
        this.messageManager = messageManager;
        
        //Cria a thread de atualizacao
        this.atualizacao = new PacketSendingRequestThread(this.messageManager);
    }
    
    public void TratarMensagemResposta(String NICK_FROM, String CRYPTO_TYPE, String MSG_TYPE, String MSG_TEXT, String MSG_DTTM)
    {
        //Mensagem comum
        List listaDadosPaineis = mapaPaineis.get(NICK_FROM);
        JPanel PainelConversa;

        if(listaDadosPaineis == null)
        {
            //Abrir uma nova aba para o id em questão
            this.abreNovaAba(NICK_FROM);

            //Pegar de novo o painel
            listaDadosPaineis = mapaPaineis.get(NICK_FROM);
        }

        PainelConversa = (JPanel) listaDadosPaineis.get(0);
        
        //Tipo de Mensagem
        if(MSG_TYPE.equals("1"))
        {   
            //Pegar o tipo de criptografia
            String DECRYPTED_TEXT = "";
            
            //Sem criptografia
            if(CRYPTO_TYPE.equals("1"))
                DECRYPTED_TEXT = MSG_TEXT;
            
            if(CRYPTO_TYPE.equals("2"))
            {
                try 
                {
                    if(this.chaveSimetrica == null)
                    {
                        Exception e = new Exception("Você recebeu uma mensagem, porém não possui a chave necessária para desencriptá-la");
                        throw(e);
                    }
                    
                    DECRYPTED_TEXT = ClientGUI2.ChaveSimetricaDecrypt(ClientGUI2.converteStringParaArrayDeBytes(MSG_TEXT), this.chaveSimetrica);
                }
                catch (Exception ex) 
                {
                    System.out.println("Exceção: " + ex);
                }
            }
            
            if(CRYPTO_TYPE.equals("3"))
            {
                DECRYPTED_TEXT = Asymmetric_RSA.decriptografa(ClientGUI2.converteStringParaArrayDeBytes(MSG_TEXT), Asymmetric_RSA.CHAVE_PRIVADA);
            }
            
            //Colocar a mensagem na janela que já existe
            this.appendText(NICK_FROM, Integer.parseInt(CRYPTO_TYPE), MSG_DTTM, DECRYPTED_TEXT, MSG_TEXT, PainelConversa);

            //Selectionar aba
            PainelAbas.remove(PainelInterior);
            PainelAbas.setSelectedComponent(PainelConversa);
                
        }
        else
        {
            //Acordo de chaves
            
            //Guardar a chave recebida
            this.chaveSimetrica = MSG_TEXT;
            
            //Escrever na saída que a chave foi recebida
            this.appendKeyText(NICK_FROM, Integer.valueOf(CRYPTO_TYPE), MSG_DTTM, PainelConversa);
        }
    }
    
    private void appendText(String NICK_FROM, int CRYPTO_TYPE, String MSG_DTTM, String MSG_TEXT, String CIPHER_TEXT, JPanel Painel)
    {
        //Pegar TextArea da conversa
        JTextPane conversa;
        
        //Se o NICK_FROM sou eu, logo eu estou mandando uma mensagem na conversa ativa
        if(NICK_FROM == this.userName)
             conversa = (JTextPane) mapaPaineis.get(PainelAbas.getTitleAt(PainelAbas.getSelectedIndex())).get(1);
        else
            conversa = (JTextPane) mapaPaineis.get(NICK_FROM).get(1);
        
        String mensagemPreparada = "";
        switch(CRYPTO_TYPE)
        {
            case 1:
                mensagemPreparada = "Tipo de Criptografia: Nenhuma\r\n" + NICK_FROM + " disse em " + MSG_DTTM + "\r\n" + MSG_TEXT + "\r\n\r\n";
                break;
            case 2:
                mensagemPreparada = "Tipo de Criptografia: Chave Simétrica\r\n" + NICK_FROM + " disse em " + MSG_DTTM + "\r\nTexto cifrado: " + CIPHER_TEXT + "\r\nTexto decodificado: " + MSG_TEXT + "\r\n\r\n";
                break;
            case 3:
                mensagemPreparada = "Tipo de Criptografia: Chave Assimétrica\r\n" + NICK_FROM + " disse em " + MSG_DTTM + "\r\nTexto cifrado: " + CIPHER_TEXT + "\r\nTexto decodificado: " + MSG_TEXT + "\r\n\r\n";
                break;
        }
        
        conversa.setText(conversa.getText() + mensagemPreparada);
    }
    
    //Mensagem qaundo é ENVIADO ou RECEBIDO um acordo de chaves
    private void appendKeyText(String NICK_FROM, int CRYPTO_TYPE, String MSG_DTTM, JPanel Painel)
    {
        //Pegar TextArea da conversa
        JTextPane conversa;
        
        //Se o NICK_FROM sou eu, logo eu estou mandando uma mensagem na conversa ativa
        if(NICK_FROM == this.userName)
             conversa = (JTextPane) mapaPaineis.get(PainelAbas.getTitleAt(PainelAbas.getSelectedIndex())).get(1);
        else
            conversa = (JTextPane) mapaPaineis.get(NICK_FROM).get(1);
        
        String mensagemPreparada = "";
        
        switch(CRYPTO_TYPE)
        {
            case 2:
            //Criptografia de chave simétrica
            mensagemPreparada =  "Criptografia de Chave Simétrica\r\n" 
                    + NICK_FROM + " gerou a chave AES em " 
                    + MSG_DTTM + "\r\n" + this.chaveSimetrica 
                    + "\r\nChave enviada pelo canal de rede"
                    +"\r\n\r\n";
            break;
        }
        
        conversa.setText(conversa.getText() + mensagemPreparada);
    }
    
    //Método que escreve uma string qualquer na aba ativa
    private void appendInformText(String texto)
    {
        JTextPane conversa;
        
        conversa = (JTextPane) mapaPaineis.get(PainelAbas.getTitleAt(PainelAbas.getSelectedIndex())).get(1);
        
        texto = texto + "\r\n\r\n";
        conversa.setText(conversa.getText() + texto);
    }
    
    private void abreNovaAba(String textoAba)
    {
        //Abrir uma nova aba para conversar com o novo usuario
        JPanel adicao = new JPanel();
        JButton ad_Enviar = new JButton();
        JTextPane ad_CaixaTexto = new JTextPane();
        JTextPane ad_Conversa = new JTextPane();
        JScrollPane ad_ScrollConversa = new JScrollPane();
        JScrollPane ad_ScrollCaixaTexto = new JScrollPane();
        JRadioButton ad_Cripto1 = new JRadioButton();
        JRadioButton ad_Cripto2 = new JRadioButton();
        JRadioButton ad_Cripto3 = new JRadioButton();
        ButtonGroup ad_ButtonGroup = new ButtonGroup();

        ad_CaixaTexto.setAutoscrolls(false);
        ad_ScrollCaixaTexto.setViewportView(ad_CaixaTexto);

        ad_Conversa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ad_Conversa.setFocusable(false);
        ad_ScrollConversa.setViewportView(ad_Conversa);

        ad_Enviar.setText("Enviar");
        ad_Enviar.addActionListener(new java.awt.event.ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEnviarActionPerformed(evt);
            }
        });

        ad_ButtonGroup.add(ad_Cripto1);
        ad_Cripto1.setSelected(true);
        ad_Cripto1.setText("Sem Criptografia");

        ad_ButtonGroup.add(ad_Cripto2);
        ad_Cripto2.setText("Chave Simétrica");

        ad_ButtonGroup.add(ad_Cripto3);
        ad_Cripto3.setText("Chave Assimétrica");

        javax.swing.GroupLayout adicaoLayout = new javax.swing.GroupLayout(adicao);
        adicao.setLayout(adicaoLayout);

        adicaoLayout.setHorizontalGroup(
        adicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicaoLayout.createSequentialGroup()
                .addGroup(adicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ad_ScrollCaixaTexto)
                    .addGroup(adicaoLayout.createSequentialGroup()
                        .addComponent(ad_Cripto1)
                        .addGap(18, 18, 18)
                        .addComponent(ad_Cripto2)
                        .addGap(18, 18, 18)
                        .addComponent(ad_Cripto3)
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ad_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(ad_ScrollConversa)
        );

        adicaoLayout.setVerticalGroup(
            adicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adicaoLayout.createSequentialGroup()
                .addComponent(ad_ScrollConversa, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ad_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adicaoLayout.createSequentialGroup()
                        .addComponent(ad_ScrollCaixaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ad_Cripto1)
                            .addComponent(ad_Cripto2)
                            .addComponent(ad_Cripto3)))))
        );

        List<Component> listaDados = new ArrayList<Component>();
        listaDados.add(adicao);
        listaDados.add(ad_Conversa);
        listaDados.add(ad_CaixaTexto);
        listaDados.add(ad_Cripto1);
        listaDados.add(ad_Cripto2);
        listaDados.add(ad_Cripto3);
        
        PainelAbas.add(textoAba, adicao);
        mapaPaineis.put(textoAba, listaDados);
    }
    
    //Métodos de encriptação e decriptação com AES - Chave Simétrica
    
    public static byte[] ChaveSimetricaEncrypt(String textopuro, String chaveencriptacao) throws Exception {
        Cipher encripta = Cipher.getInstance("AES/CBC/PKCS5Padding", "SunJCE");
        SecretKeySpec key = new SecretKeySpec(chaveencriptacao.getBytes("UTF-8"), "AES");
        encripta.init(Cipher.ENCRYPT_MODE, key,new IvParameterSpec(IV.getBytes("UTF-8")));
        return encripta.doFinal(textopuro.getBytes("UTF-8"));
    }
   
    public static String ChaveSimetricaDecrypt(byte[] textoencriptado, String chaveencriptacao) throws Exception{
            Cipher decripta = Cipher.getInstance("AES/CBC/PKCS5Padding", "SunJCE");
            SecretKeySpec key = new SecretKeySpec(chaveencriptacao.getBytes("UTF-8"), "AES");
            decripta.init(Cipher.DECRYPT_MODE, key,new IvParameterSpec(IV.getBytes("UTF-8")));
            return new String(decripta.doFinal(textoencriptado),"UTF-8");
    }
         
    public static byte[] converteStringParaArrayDeBytes(String texto)
    {
        String[] quebra = texto.split(",");
        
        //O primeiro e o último elementos têm um colchete - remover
        quebra[0] = quebra[0].substring(1);
        quebra[quebra.length - 1] = quebra[quebra.length - 1].substring(1, quebra[quebra.length - 1].length() - 1);
        
        byte[] retorno = new byte[quebra.length];
        
        int i;
        for(i = 0; i < retorno.length; i++)
            retorno[i] = Byte.valueOf(quebra[i].trim());
        
        return retorno;
    }
}
