/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.deitel.messenger;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 *
 * @author ctcca
 */
public class ClientGUI2 extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI2
     */
    public ClientGUI2() {
        initComponents();
        this.mapaPaineis = new HashMap<String, JPanel>();
        
        this.loadContacts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PainelAbas = new javax.swing.JTabbedPane();
        PainelInterior = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CaixaTexto = new javax.swing.JTextPane();
        BotaoEnviar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Conversa = new javax.swing.JTextPane();
        Cripto1 = new javax.swing.JRadioButton();
        Cripto2 = new javax.swing.JRadioButton();
        Cripto3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CaixaTexto.setAutoscrolls(false);
        CaixaTexto.setEnabled(false);
        jScrollPane2.setViewportView(CaixaTexto);

        BotaoEnviar.setText("Enviar");
        BotaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEnviarActionPerformed(evt);
            }
        });

        Conversa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Conversa.setFocusable(false);
        jScrollPane3.setViewportView(Conversa);

        buttonGroup1.add(Cripto1);
        Cripto1.setSelected(true);
        Cripto1.setText("Sem Criptografia");
        Cripto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cripto1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Cripto2);
        Cripto2.setText("Chave Simétrica");

        buttonGroup1.add(Cripto3);
        Cripto3.setText("Chave Assimétrica");
        Cripto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cripto3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelInteriorLayout = new javax.swing.GroupLayout(PainelInterior);
        PainelInterior.setLayout(PainelInteriorLayout);
        PainelInteriorLayout.setHorizontalGroup(
            PainelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInteriorLayout.createSequentialGroup()
                .addGroup(PainelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(PainelInteriorLayout.createSequentialGroup()
                        .addComponent(Cripto1)
                        .addGap(18, 18, 18)
                        .addComponent(Cripto2)
                        .addGap(18, 18, 18)
                        .addComponent(Cripto3)
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane3)
        );
        PainelInteriorLayout.setVerticalGroup(
            PainelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInteriorLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelInteriorLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cripto1)
                            .addComponent(Cripto2)
                            .addComponent(Cripto3)))))
        );

        PainelAbas.addTab("Inicie uma conversa", PainelInterior);

        jButton1.setText("Adicionar Contato");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item1", "item2", "item3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelAbas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() == 2)
        {            
            //Duplo ou Triplo clique detectado
            int index = jList1.locationToIndex(evt.getPoint());
            String textoAba = this.jList1.getModel().getElementAt(index);
            
            //Se a aba já existir, apenas deixá-la visível
            for(int i = 0; i < PainelAbas.getTabCount(); i++)
            {
                if(PainelAbas.getTitleAt(i)==textoAba)
                {
                    PainelAbas.setSelectedIndex(i);
                    return;
                }
                
            }
            
            //Abrir uma nova aba para conversar com o novo usuario
            JPanel adicao = new JPanel();
            JButton ad_Enviar = new JButton();
            JTextPane ad_CaixaTexto = new JTextPane();
            JTextPane ad_Conversa = new JTextPane();
            JScrollPane ad_ScrollConversa = new JScrollPane();
            JScrollPane ad_ScrollCaixaTexto = new JScrollPane();
            JRadioButton ad_Cripto1 = new JRadioButton();
            JRadioButton ad_Cripto2 = new JRadioButton();
            JRadioButton ad_Cripto3 = new JRadioButton();
            ButtonGroup ad_ButtonGroup = new ButtonGroup();
            
            ad_CaixaTexto.setAutoscrolls(false);
            ad_ScrollCaixaTexto.setViewportView(ad_CaixaTexto);
            
            ad_Conversa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            ad_Conversa.setFocusable(false);
            ad_ScrollConversa.setViewportView(ad_Conversa);
            
            ad_Enviar.setText("Enviar");
            ad_Enviar.addActionListener(new java.awt.event.ActionListener() 
            {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotaoEnviarActionPerformed(evt);
                }
            });
            
            ad_ButtonGroup.add(ad_Cripto1);
            ad_Cripto1.setSelected(true);
            ad_Cripto1.setText("Sem Criptografia");

            ad_ButtonGroup.add(ad_Cripto2);
            ad_Cripto2.setText("Chave Simétrica");

            ad_ButtonGroup.add(ad_Cripto3);
            ad_Cripto3.setText("Chave Assimétrica");

            javax.swing.GroupLayout adicaoLayout = new javax.swing.GroupLayout(adicao);
            adicao.setLayout(adicaoLayout);
            
            adicaoLayout.setHorizontalGroup(
            adicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(adicaoLayout.createSequentialGroup()
                    .addGroup(adicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ad_ScrollCaixaTexto)
                        .addGroup(adicaoLayout.createSequentialGroup()
                            .addComponent(ad_Cripto1)
                            .addGap(18, 18, 18)
                            .addComponent(ad_Cripto2)
                            .addGap(18, 18, 18)
                            .addComponent(ad_Cripto3)
                            .addGap(0, 206, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ad_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(ad_ScrollConversa)
            );
            
            adicaoLayout.setVerticalGroup(
                adicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adicaoLayout.createSequentialGroup()
                    .addComponent(ad_ScrollConversa, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(adicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ad_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(adicaoLayout.createSequentialGroup()
                            .addComponent(ad_ScrollCaixaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(adicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ad_Cripto1)
                                .addComponent(ad_Cripto2)
                                .addComponent(ad_Cripto3)))))
            );
            
            PainelAbas.add(textoAba, adicao);
            
            //Tentar remover a primeira aba
            PainelAbas.remove(PainelInterior);
            PainelAbas.setSelectedIndex(PainelAbas.getComponentCount()-1);
            
            this.mapaPaineis.put(textoAba, adicao);
        }
        
    }//GEN-LAST:event_jList1MouseClicked

    private void BotaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoEnviarActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

    }//GEN-LAST:event_jList1ValueChanged

    private void Cripto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cripto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cripto1ActionPerformed

    private void Cripto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cripto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cripto3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI2().setVisible(true);
            }
        });
    }
    
    public void loadContacts()
    {
        File arqContatos = new File("files/contatos.rp2");
        
        if(arqContatos.exists())
        {
            String contato;
            
            try
            {
                FileReader reader = new FileReader(arqContatos);
                BufferedReader reader2 = new BufferedReader(reader);
                DefaultListModel model = new DefaultListModel<String>();
                
                while((contato = reader2.readLine()) != null)
                {
                    model.addElement(contato);
                }
                
                jList1.setModel(model);
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEnviar;
    private javax.swing.JTextPane CaixaTexto;
    private javax.swing.JTextPane Conversa;
    private javax.swing.JRadioButton Cripto1;
    private javax.swing.JRadioButton Cripto2;
    private javax.swing.JRadioButton Cripto3;
    private javax.swing.JTabbedPane PainelAbas;
    private javax.swing.JPanel PainelInterior;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    
    //Variaveis de controle de pagina
    private HashMap<String,javax.swing.JPanel> mapaPaineis;
}
